services:
  app:
    image: docker-registry.guarico.gob.ve/cgt:develop
    container_name: cgt-develop
    restart: unless-stopped
    ports:
      - '5102:80'
    networks:
      - cgt-network-develop

networks:
  cgt-network-develop:
    name: cgt-network-develop
    driver: bridge
