name: Build Main and Publish image to Docker Hub
on:
  push:
    branches:
      - main

  
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: docker build . -t docker-registry.guarico.gob.ve/cgt:latest
      - name: push image to Docker Registry
        run: |
          docker push docker-registry.guarico.gob.ve/cgt:latest
      - name: Notify Portainer to pull the new image
        # Usa curl para llamar al webhook de Portainer
        run: |
          # Importante: Guarda el webhook como un 'secret' en GitHub para mayor seguridad.
          curl -X POST https://portainer.guarico.gob.ve/api/webhooks/e19ce850-b154-418b-8dd1-691668fda062