name: Build Demo and Publish image to Docker Hub
on:
  push:
    branches:
      - develop

  
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: docker build . -t docker-registry.guarico.gob.ve/cgt:develop
      - name: push image to Docker Registry
        run: |
          docker push docker-registry.guarico.gob.ve/cgt:develop
