name: Build Demo and Publish image to Docker Hub
on:
  push:
    branches:
      - develop

  
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build image
        run: docker build . -t docker-registry.guarico.gob.ve/cgt:develop
      - name: push image to Docker Registry
        run: |
          docker push docker-registry.guarico.gob.ve/cgt:develop
      - name: Notify Portainer to pull the new image
        # Usa curl para llamar al webhook de Portainer
        run: |
          # Importante: Guarda el webhook como un 'secret' en GitHub para mayor seguridad.
          curl -X POST https://portainer.guarico.gob.ve/api/webhooks/57d58af4-248b-4d65-9a21-1aa8852b6efc